//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNTT3_NguyenVanHuynh_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    }
}
